// This file is generated by swc-bff
// Do not edit this file manually
type Decoder<T> = { parse: (value: unknown) => T };
type DecodersOfKV<T> = {
  [K in keyof T]: Decoder<T[K]>;
};
export declare const buildDecoders: <T>() => DecodersOfKV<T>;
// export declare const meta: any;
import { Env, Hono } from "hono";

type OpenApiServer = any;

export declare const registerRouter: <
  E extends Env,
  S,
  BasePath extends string,
>(options: {
  app: Hono<E, S, BasePath>;
  router: any;
  openApi: { servers: OpenApiServer[] };
}) => Hono<E, S, BasePath>;
