import "./globals.css";
import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import { Providers } from "./providers";
import { ReactQueryProvider } from "@/components/query-client-provider";
import { getServerSession } from "next-auth";
import { Layout } from "@/components/layout";
import { authOptions } from "./api/auth/[...nextauth]/options";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      style={{
        height: "100%",
      }}
    >
      <body className={[inter.className, "h-full"].join(" ")}>
        <Suspense fallback={<>Loading...</>}>
          <Providers>
            <Theme
              className="h-full"
              accentColor="grass"
              grayColor="gray"
              radius="full"
            >
              <ReactQueryProvider>
                <Layout>{children}</Layout>
              </ReactQueryProvider>
            </Theme>
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
